### PR TITLE
Milestone Icons

### PR DESCRIPTION
**Pull request by SylentButDedly**
Adds icons to applicable milestone days! I just pulled the item watermarks (or icons from triumphs) and cut them up a bit. Hovering over a day with an icon will also zoom in on it a bit.

If you have any other ideas for icons to add to the other events let me know! Could maybe also do the trials release, iron banner, raids, etc., not sure if that'd be too cluttered

Also added a few missing event days from 2017/early 2018 that I hadn't noticed

It's possible there's a nicer, more automated way of handling the background images but I couldn't think of any

image
firefox_2EVRf2pnC5
image

### CODE REVIEW

**Comment by chrisfried** [comment]
I did some experimenting around making the icons stand out against the square they're on, regardless of the color of the square. Current solution is to invert the color. Not sure if I like it.

image

**Comment by chrisfried** [comment]
Definitely stands out better against red squares.

image

**Comment by chrisfried** [comment]
Pushed my changes into the PR if you want to play with them further.

**Comment by chrisfried** [comment]
The inverted colors are growing on me. Merged.

**Comment by SylentButDedly** [comment]
Haven't had a chance to play with them but I agree that stands out better!

**Pull request merged**
